In [1]:
import numpy as np

# Creating an array (vector)

## directly

In [2]:
my_vec = np.array([1,2,3,4,5])

In [3]:
my_vec

array([1, 2, 3, 4, 5])

## from a list

In [4]:
my_list = [x for x in range(10)]

In [5]:
my_vec = np.array(my_list)

In [6]:
my_vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## built-in methods

In [7]:
my_vec = np.arange(1, 10)

In [8]:
my_vec

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_vec = np.arange(1,10, 2)

In [10]:
my_vec

array([1, 3, 5, 7, 9])

In [11]:
np.zeros(10) # array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((10, 10)) # matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [15]:
np.linspace(0, 10, 15) # space in range 0 to 10 inclusevely evenly split into 15 chunks

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

## eye for identical matrix

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random module

### rand - _random number in range 0 to 1_

In [17]:
np.random.rand(10)

array([0.92376875, 0.7575951 , 0.61881526, 0.81443583, 0.60133207,
       0.04065075, 0.47125259, 0.07673596, 0.7350693 , 0.17123354])

In [18]:
np.random.rand(2, 5)

array([[0.44734462, 0.30183276, 0.7949809 , 0.14988247, 0.2082355 ],
       [0.42129501, 0.85661233, 0.55343234, 0.97752123, 0.52881924]])

### randn - _sample (or samples) from the "standard normal" distribution [σ = 1]_

In [19]:
np.random.randn(10)

array([ 1.95388976,  0.27151157, -0.03109042,  0.09336029,  1.00040504,
       -0.21007095, -1.49465244, -0.30844068,  0.9518033 , -1.40572226])

In [20]:
np.random.randn(2, 5)

array([[ 2.43150374,  0.66081539,  0.69638705, -1.31427148,  0.36612266],
       [-1.41635937,  1.05440186,  0.44853365,  1.33101315, -0.06963006]])

### randint - _returns array of integers in given range_

In [21]:
np.random.randint(2, 15) # returns an integer

12

In [22]:
np.random.randint(2, 15, 3)

array([ 6, 10,  9])

### seed - _used to set the random state_

In [23]:
np.random.seed(10)
print(np.random.rand(5))
print()
np.random.seed(5)
print(np.random.rand(5))
print()
np.random.seed(10)
print(np.random.rand(5))
print()
np.random.seed(5)
print(np.random.rand(5))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]

[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119]

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]

[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119]


# Creating a matrix

## randn

In [24]:
my_mat = np.random.randn(2, 3) # 2 rows, 3 columns for 2dimensional vector 

In [25]:
my_mat

array([[ 1.36758552,  0.57470769, -1.88576241],
       [ 0.17092537, -0.40309331,  1.63762849]])

# Reshape matrix 

Returns an array containing the same data with a new shape.  
Reshape size must be square numbers like 2x2,3x3,4x4

In [26]:
array = np.arange(36) # creating an array
array.reshape(6,6) # reshaping it into a matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [27]:
array.reshape(6,5) # is impossible

ValueError: cannot reshape array of size 36 into shape (6,5)

In [28]:
array.reshape(3, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [29]:
array.reshape(4, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

# Matrix transformation

In [30]:
my_mat.T

array([[ 1.36758552,  0.17092537],
       [ 0.57470769, -0.40309331],
       [-1.88576241,  1.63762849]])

Now we have a 3dimensional vector with 2 columns

In [31]:
my_mat2 = np.random.randn(3, 2)

In [32]:
my_mat2

array([[-0.60529785, -1.59441507],
       [ 0.91187364, -1.44384155],
       [ 1.82444017,  1.45762512]])

# Arithmetic

In [33]:
arr = np.arange(0,11)

## With numbers

In [38]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
arr-20

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10])

In [40]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [41]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

## Array and array

In [34]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [37]:
arr/arr

/tmp/ipykernel_28939/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# Matrix

In [43]:
my_mat.T + my_mat2 # addition is only possible for matrixes having same dimensions

array([[ 0.76228768, -1.42348971],
       [ 1.48658133, -1.84693487],
       [-0.06132224,  3.09525361]])

In [44]:
my_mat.T - my_mat2

array([[ 1.97288337,  1.76534044],
       [-0.33716595,  1.04074824],
       [-3.71020257,  0.18000337]])

In [45]:
my_mat @ my_mat2

array([[-3.74419646, -5.75902048],
       [ 2.51672427,  2.69652532]])

# Array Functions


In [46]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [47]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [48]:
np.log(arr)

/tmp/ipykernel_28939/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Statistics

In [52]:
arr = np.arange(0,11)
print(f'Sum: \t\t\t{arr.sum()}')
print(f'Mean: \t\t\t{arr.mean()}')
print(f'Max: \t\t\t{arr.max()}')
print(f'Min: \t\t\t{arr.min()}')
print(f'Variance: \t\t{arr.var()}')
print(f'Standard deviation\t{arr.std()}')

Sum: 			55
Mean: 			5.0
Max: 			10
Min: 			0
Variance: 		10.0
Standard deviation	3.1622776601683795


# Array concatenation

In [54]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr3 = np.array([11, 12, 13, 14, 15])
con_arr = np.concatenate([arr1, arr2, arr3])
con_arr  # just cncatenated array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
con_arr.reshape(
    5, 3
)  # each of 3 arrays had 5 items - we get a 2dimensional matrix with 5 rows and 3 columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# Staking arrays

In [58]:
odd_array = np.array([[1, 3], [7, 9]])
even_array = np.array([[2, 4], [6, 8]])

# horizontal staking
np.hstack([odd_array, even_array])

array([[1, 3, 2, 4],
       [7, 9, 6, 8]])

In [59]:
# vertical staking
np.vstack([odd_array, even_array])

array([[1, 3],
       [7, 9],
       [2, 4],
       [6, 8]])

In [60]:
# depth-wise stacking
np.dstack([odd_array, even_array])

array([[[1, 2],
        [3, 4]],

       [[7, 6],
        [9, 8]]])

# Splitting arrays

In [61]:
array = np.array([
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35
])

In [63]:
arr1, arr2, arr3, arr4 = np.split(array, 4) # can be only splitted in equal chunks, i.e array % n == 0

In [64]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[0 1 2 3 4 5 6 7 8]
[ 9 10 11 12 13 14 15 16 17]
[18 19 20 21 22 23 24 25 26]
[27 28 29 30 31 32 33 34 35]
